MB-100 Increase sleep in TestCreateReplicatedIndexesBeforeRebalance
The replicated indexes created by this test take some time after
returning to actually complete building (even though a non-deferred N1QL
"create index" statement should be executed synchronously), so sleeps
are needed between these. If the sleeps are not long enough, especially
for the slow CI Bot machine, then the test can fail with error

TestCreateReplicatedIndexesBeforeRebalance: Error executing N1QL
create index set14_idx_2REPLICAS_isActive_age on `default`(isActive, age)
  with {"num_replica":2}: [5000] GSI CreateIndex() - cause: Encountered
  transient error.  Index creation will be retried in background.
  Error: Index set14_idx_2REPLICAS_isActive_age will retry building in
  the background for reason: Build Already In Progress. Keyspace default.

5-sec sleeps are not always quite enough for the CI Bot machine, so this
patch increases them to 6 seconds.

Change-Id: I304e20b55a6ba76aee6df0e87af8021ac1752725