Revert "MB-54512:[Backport MB 52462 to 6.6.6] Handle Panics in go routines while loading snapshot"
This reverts commit 08b3aecc3958317aa4544b3efb3a6aad09c90a4c.

Reason for revert: Breaks build:
12:53:04 # github.com/couchbase/indexing/secondary/memdb
12:53:04 ../../../../../../goproj/src/github.com/couchbase/indexing/secondary/memdb/memdb.go:1095:6: undefined: logging
12:53:04 ../../../../../../goproj/src/github.com/couchbase/indexing/secondary/memdb/memdb.go:1096:6: undefined: logging

Change-Id: I337f330f742bf70e7dacdaa81e21f217dbace9e9